### ISSUE TITLE
Where I can get Reference for this line

### ISSUE THREAD

**Issue by didiroesmana** [efi/gephi-cw#2]
gephi-cw/src/de/uni_leipzig/informatik/asv/gephi/chinesewhispers/ChineseWhispersClusterer.java

at line 138 - 140
you use propagation ( TOP, LOG , DIST LOG  and VOTE )
where can I find the reference about that formula ?
I need to know the reference for my UndergraduateThesis

Thanks in advance

**Comment by efi** [comment]
Hi. The different propagation methods are adopted from the explanation page of the original implementation:  http://wortschatz.informatik.uni-leipzig.de/~cbiemann/software/CW.html

The scientific paper for this is available at http://wortschatz.uni-leipzig.de/~cbiemann/pub/2006/BiemannTextGraph06.pdf
